### ISSUE TITLE
Kin balance = 0 when re-installing app

### ISSUE THREAD

**Issue by phips28** [kinecosystem/kin-ecosystem-ios-sdk#17]
I have a test setup to test the SDK. 

After re-installing the app on iOS Simulator the balance is 0 Kin - but I had a Kin balance before the re-install.
The transaction history is correct as you can see in the screenshot, but balance shows 0 - therefore use cannot use any `spend` function.

![simulator screen shot - iphone 6 - 2018-10-08 at 08 58 51](https://user-images.githubusercontent.com/3694800/46595388-6ae5ec80-cad8-11e8-8fb5-1bb7b2a79672.png)

**Comment by phips28** [comment]
Same issue on android:

<img width="365" alt="screenshot 2018-10-12 08 16 45" src="https://user-images.githubusercontent.com/3694800/46851246-2c617200-cdf7-11e8-85de-e05de137f62c.png">

**Comment by phips28** [comment]
as we discussed in the slack channel, balance=0 is due to the fact that the **private key** is stored on the device and gets lost after re-installing.
and the **history** is coming from kin backend by `userId`

**Comment by Elaz** [comment]
This issue is obsolete, closing.
